# Requires that buidld_host_dicts.yml has run before
---
- name: Dump/flush dynamic zone changes to disk/zone file
  ansible.builtin.command: "rndc sync -clean {{ item.name }}"
  with_items:
    - "{{ bind_zones }}"
  when: >
    (item.create_forward_zones is not defined or item.create_forward_zones) and
    ((item.type is defined and item.type == 'primary') or
    (item.type is not defined and zone_auxiliary[item.name]['primaries_dict'] is defined and
    (host_all_addresses | intersect(zone_auxiliary[item.name]['primaries_dict'].keys()) | length > 0))) and
    item.update_policy is defined or item.allow_update is defined
  notify: Reload bind
  changed_when: false
  tags: bind

- name: Dump/flush dynamic ipv4 reverse zone changes to disk/zone file
  ansible.builtin.command: "rndc sync -clean {{ ('.'.join(item.1.replace(item.1+'.','').split('.')[::-1])) }}.in-addr.arpa"
  with_subelements:
    - "{{ bind_zones }}"
    - networks
    - flags:
      skip_missing: true
  loop_control:
    label: "{{ item.1 }}"
  when: >
    (item.create_reverse_zones is not defined or item.create_reverse_zones) and
    ((item[0].type is defined and item[0].type == 'primary') or
    (item[0].type is not defined and zone_auxiliary[item[0].name]['primaries_dict'] is defined and
    (host_all_addresses | intersect(zone_auxiliary[item[0].name]['primaries_dict'].keys()) | length > 0))) and
    item[0].update_policy is defined or item[0].allow_update is defined
  notify: Reload bind
  changed_when: false
  tags: bind

- name: Dump/flush dynamic ipv6 reverse zone changes to disk/zone file
  ansible.builtin.command: "rndc sync -clean {{ (item.1 | ipaddr('revdns'))[-(9+(item.1|regex_replace('^.*/','')|int)//2):-1] }}"
  with_subelements:
    - "{{ bind_zones }}"
    - ipv6_networks
    - flags:
      skip_missing: true
  loop_control:
    label: "{{ item.1 }}"
  when: >
    (item.create_reverse_zones is not defined or item.create_reverse_zones) and
    ((item[0].type is defined and item[0].type == 'primary') or
    (item[0].type is not defined and zone_auxiliary[item[0].name]['primaries_dict'] is defined and
    (host_all_addresses | intersect(zone_auxiliary[item[0].name]['primaries_dict'].keys()) | length > 0))) and
    item[0].update_policy is defined or item[0].allow_update is defined
  notify: Reload bind
  changed_when: false
  tags: bind
