---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:

    # Only collect network facts to reduce setup time
    - name: Gathering Facts
      setup:
        gather_subset:
          - 'network'

    - name: Set local_dns variable for dig
      set_fact:
        local_dns: "{{ '@' + ansible_default_ipv4.address }}"
        dns_port: 53

    - name: Set dns port for ns2
      ansible.builtin.set_fact:
        dns_port: 553
      when: "inventory_hostname == 'ns2'"

    - name: List contents of /var/lib/bind
      ansible.builtin.shell: ls -la /var/lib/bind
      when: "inventory_hostname == 'ns2'"
      ignore_errors: true
      register: result

    - debug:
        var: result

    - name: Show Log file
      ansible.builtin.shell: cat /var/lib/bind/data/named.run
      when: "inventory_hostname == 'ns2'"
      ignore_errors: true
      register: result

    - debug:
        var: result

    - name: Perform test dig
      ansible.builtin.shell: dig @localhost -p 553 ns1.acme-inc.com
      when: "inventory_hostname == 'ns2'"
      ignore_errors: true
      register: result

    - debug:
        var: result
      
    - name: IPv4 Forward lookups
      assert:
        that:
          - lookup('dig', 'ns1.acme-inc.com', local_dns, port=dns_port)    == '10.11.0.1'
          - lookup('dig', 'ns2.acme-inc.com', local_dns, port=dns_port)     == '10.11.0.2'
          - lookup('dig', 'srv001.acme-inc.com', local_dns, port=dns_port)  == '10.11.1.1'
          - lookup('dig', 'srv002.acme-inc.com', local_dns, port=dns_port)  == '10.11.1.2'
          - lookup('dig', 'mail001.acme-inc.com', local_dns, port=dns_port) == '10.11.2.1'
          - lookup('dig', 'mail002.acme-inc.com', local_dns, port=dns_port) == '10.11.2.2'
          - lookup('dig', 'mail003.acme-inc.com', local_dns, port=dns_port) == '10.11.2.3'
          - lookup('dig', 'srv010.acme-inc.com', local_dns, port=dns_port)  == '10.11.0.10'
          - lookup('dig', 'srv011.acme-inc.com', local_dns, port=dns_port)  == '10.11.0.11'
          - lookup('dig', 'srv012.acme-inc.com', local_dns, port=dns_port)  == '10.11.0.12'
          - lookup('dig', 'srv001.example.com', local_dns, port=dns_port)   == '192.0.2.1'
          - lookup('dig', 'srv002.example.com', local_dns, port=dns_port)   == '192.0.2.2'
          - lookup('dig', 'mail001.example.com', local_dns, port=dns_port)  == '192.0.2.10'

    - name: IPv4 Reverse lookups
      assert:
        that:
          - lookup('dig', '10.11.0.1/PTR', local_dns, port=dns_port)  == 'ns1.acme-inc.com.'
          - lookup('dig', '10.11.0.2/PTR', local_dns, port=dns_port)  == 'ns2.acme-inc.com.'
          - lookup('dig', '10.11.1.1/PTR', local_dns, port=dns_port)  == 'srv001.acme-inc.com.'
          - lookup('dig', '10.11.1.2/PTR', local_dns, port=dns_port)  == 'srv002.acme-inc.com.'
          - lookup('dig', '10.11.2.1/PTR', local_dns, port=dns_port)  == 'mail001.acme-inc.com.'
          - lookup('dig', '10.11.2.2/PTR', local_dns, port=dns_port)  == 'mail002.acme-inc.com.'
          - lookup('dig', '10.11.2.3/PTR', local_dns, port=dns_port)  == 'mail003.acme-inc.com.'
          - lookup('dig', '10.11.0.10/PTR', local_dns, port=dns_port) == 'srv010.acme-inc.com.'
          - lookup('dig', '10.11.0.11/PTR', local_dns, port=dns_port) == 'srv011.acme-inc.com.'
          - lookup('dig', '10.11.0.12/PTR', local_dns, port=dns_port) == 'srv012.acme-inc.com.'
          - lookup('dig', '192.0.2.1/PTR', local_dns, port=dns_port)  == 'srv001.example.com.'
          - lookup('dig', '192.0.2.2/PTR', local_dns, port=dns_port)  == 'srv002.example.com.'
          - lookup('dig', '192.0.2.10/PTR', local_dns, port=dns_port) == 'mail001.example.com.'

    - name: IPv4 Alias lookups
      assert:
        that:
          - lookup('dig', 'www.acme-inc.com', local_dns, port=dns_port)      == '10.11.1.1'
          - lookup('dig', 'mysql.acme-inc.com', local_dns, port=dns_port)    == '10.11.1.2'
          - lookup('dig', 'smtp.acme-inc.com', local_dns, port=dns_port)     == '10.11.2.1'
          - lookup('dig', 'mail-in.acme-inc.com', local_dns, port=dns_port)  == '10.11.2.1'
          - lookup('dig', 'imap.acme-inc.com', local_dns, port=dns_port)     == '10.11.2.3'
          - lookup('dig', 'mail-out.acme-inc.com', local_dns, port=dns_port) == '10.11.2.3'
          - lookup('dig', 'www.example.com', local_dns, port=dns_port)       == '192.0.2.1'

    - name: IPv6 Forward lookups
      assert:
        that:
          - lookup('dig', 'srv001.acme-inc.com/AAAA', local_dns, port=dns_port)  == '2001:db8::1'
          - lookup('dig', 'srv002.acme-inc.com/AAAA', local_dns, port=dns_port)  == '2001:db8::2'
          - lookup('dig', 'mail001.acme-inc.com/AAAA', local_dns, port=dns_port) == '2001:db8::d:1'
          - lookup('dig', 'mail002.acme-inc.com/AAAA', local_dns, port=dns_port) == '2001:db8::d:2'
          - lookup('dig', 'mail003.acme-inc.com/AAAA', local_dns, port=dns_port) == '2001:db8::d:3'
          - lookup('dig', 'srv001.example.com/AAAA', local_dns, port=dns_port)   == '2001:db9::1'

    - name: IPv6 Reverse lookups
      assert:
        that:
          - lookup('dig', '2001:db8::1/PTR', local_dns, port=dns_port)   == 'srv001.acme-inc.com.'
          - lookup('dig', '2001:db8::2/PTR', local_dns, port=dns_port)   == 'srv002.acme-inc.com.'
          - lookup('dig', '2001:db8::d:1/PTR', local_dns, port=dns_port) == 'mail001.acme-inc.com.'
          - lookup('dig', '2001:db8::d:2/PTR', local_dns, port=dns_port) == 'mail002.acme-inc.com.'
          - lookup('dig', '2001:db8::d:3/PTR', local_dns, port=dns_port) == 'mail003.acme-inc.com.'
          - lookup('dig', '2001:db8::d:3/PTR', local_dns, port=dns_port) == 'mail003.acme-inc.com.'
          - lookup('dig', '2001:db9::1/PTR', local_dns, port=dns_port)   == 'srv001.example.com.'

    - name: NS records lookup
      assert:
        that:
          - lookup('dig', 'acme-inc.com/NS', local_dns, port=dns_port).split(',') | sort | join(',') == 'ns1.acme-inc.com.,ns2.acme-inc.com.'
          - lookup('dig', 'example.com/NS', local_dns, port=dns_port).split(',')  | sort | join(',') == 'ns1.acme-inc.com.,ns2.acme-inc.com.'

    - name: MX records lookup
      assert:
        that:
          - lookup('dig', 'acme-inc.com/MX', local_dns, port=dns_port).split(',') | sort | join(',') == '10 mail001.acme-inc.com.,20 mail002.acme-inc.com.'
          - lookup('dig', 'example.com/MX', local_dns, port=dns_port).split(',')  | sort | join(',') == '10 mail001.example.com.'

    - name: Service records lookup
      assert:
        that:
          - lookup('dig', '_ldap._tcp.acme-inc.com/SRV', local_dns, port=dns_port) == '0 100 88 srv010.acme-inc.com.'

    - name: TXT records lookup
      assert:
        that:
          - lookup('dig', '_kerberos.acme-inc.com/TXT', local_dns, port=dns_port) == 'KERBEROS.ACME-INC.COM'
          - lookup('dig', 'acme-inc.com/TXT', local_dns, port=dns_port).split(',') | sort | join(',') == 'more text,some text'
