---

# Remark that common variables are defined in `group_vars/all.yml`

- name: Primary/Secondary with Shared Inventory
  hosts: all
  pre_tasks:
    - name: "Old Debian: Switch source repo to archive "
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: 'deb.debian.org'
        replace: 'archive.debian.org'
      when:
        - ansible_distribution == 'Debian'
        - ansible_distribution_major_version | int <= 10

  roles:
    - role: "salvoxia.bind"
