---

# Remark that common variables are defined in `group_vars/all.yml`

- name: Primary/Secondary with Shared Inventory
  hosts: dns
  pre_tasks:
    - name: Set zone-file owner
      ansible.builtin.set_fact:
        bind_zone_file_owner_override: "bind"
        bind_zone_file_group_override: "bind"
      when: ansible_distribution == 'Debian'

  roles:
    - role: "salvoxia.bind"
