---
name: CI
'on':
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "31 3 * * 1"

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos8
          - debian10
          - debian11
          - debian12
          - ubuntu2204
          - ubuntu2404

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies (CentOS 8 / Debian 10).
        run: pip3 install ansible==9.13.0 molecule molecule-docker yamllint ansible-lint docker netaddr dnspython
        if: matrix.distro == 'centos8' || matrix.distro == 'debian10'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-docker yamllint ansible-lint docker netaddr dnspython
        if: matrix.distro != 'centos8' && matrix.distro != 'debian10'

      - name: Run Molecule Primary/Secondary/Forwarder tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule Shared Inventory tests
        run: molecule test --scenario-name shared_inventory
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
