---
name: Ansible Galaxy
on:
  workflow_dispatch:
  push:
    paths:
      - "README.md"
    tags:
      - "*"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: pip3 install yamllint

      - name: Run Yamllint
        run: |
          yamllint .

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.12.2
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos8
          - debian10
          - debian11
          - debian12
          - ubuntu2204
          - ubuntu2404

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies (CentOS 8 / Debian 10).
        run: pip3 install ansible==9.13.0 molecule molecule-docker yamllint ansible-lint docker netaddr dnspython
        if: matrix.distro == 'centos8' || matrix.distro == 'debian10'

      # community.general version >= 9.5.0 is required for the 'dig' lookup filter to support the 'port' parameter
      - name: Install ansible dependencies (CentOS 8 / Debian 10).
        run: ansible-galaxy collection install community.general>=9.5.0 --force
        if: matrix.distro == 'centos8' || matrix.distro == 'debian10'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-docker yamllint ansible-lint docker netaddr dnspython
        if: matrix.distro != 'centos8' && matrix.distro != 'debian10'

      - name: Run Molecule Primary/Secondary/Forwarder tests
        run: molecule test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule Shared Inventory tests
        run: molecule test --scenario-name shared_inventory
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule Shared Inventory tests with non-standard ports
        run: molecule test --scenario-name shared_inventory_nonstandard_ports
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

  release:
    name: Release
    needs: molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'salvoxia.bind'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
